// Generated by gencpp from file robot_service/RLChooseActionRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONREQUEST_H
#define ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_service
{
template <class ContainerAllocator>
struct RLChooseActionRequest_
{
  typedef RLChooseActionRequest_<ContainerAllocator> Type;

  RLChooseActionRequest_()
    : state()  {
    }
  RLChooseActionRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::robot_service::RLChooseActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_service::RLChooseActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RLChooseActionRequest_

typedef ::robot_service::RLChooseActionRequest_<std::allocator<void> > RLChooseActionRequest;

typedef boost::shared_ptr< ::robot_service::RLChooseActionRequest > RLChooseActionRequestPtr;
typedef boost::shared_ptr< ::robot_service::RLChooseActionRequest const> RLChooseActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_service::RLChooseActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_service': ['/home/jingzhe/WorkSpace/ROS/mp500lwa4d_robot_env/src/robot_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLChooseActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLChooseActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLChooseActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c30e6364d50c603d25671fea66595c53";
  }

  static const char* value(const ::robot_service::RLChooseActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc30e6364d50c603dULL;
  static const uint64_t static_value2 = 0x25671fea66595c53ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_service/RLChooseActionRequest";
  }

  static const char* value(const ::robot_service::RLChooseActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] state\n\
";
  }

  static const char* value(const ::robot_service::RLChooseActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLChooseActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_service::RLChooseActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_service::RLChooseActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONREQUEST_H
