// Generated by gencpp from file robot_service/RLChooseActionResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONRESPONSE_H
#define ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_service
{
template <class ContainerAllocator>
struct RLChooseActionResponse_
{
  typedef RLChooseActionResponse_<ContainerAllocator> Type;

  RLChooseActionResponse_()
    : action()  {
    }
  RLChooseActionResponse_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::robot_service::RLChooseActionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_service::RLChooseActionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RLChooseActionResponse_

typedef ::robot_service::RLChooseActionResponse_<std::allocator<void> > RLChooseActionResponse;

typedef boost::shared_ptr< ::robot_service::RLChooseActionResponse > RLChooseActionResponsePtr;
typedef boost::shared_ptr< ::robot_service::RLChooseActionResponse const> RLChooseActionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_service::RLChooseActionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_service': ['/home/jingzhe/WorkSpace/ROS/mp500lwa4d_robot_env/src/robot_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLChooseActionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLChooseActionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLChooseActionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79f44d272f2ebe04451185b0dea57684";
  }

  static const char* value(const ::robot_service::RLChooseActionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79f44d272f2ebe04ULL;
  static const uint64_t static_value2 = 0x451185b0dea57684ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_service/RLChooseActionResponse";
  }

  static const char* value(const ::robot_service::RLChooseActionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] action\n\
";
  }

  static const char* value(const ::robot_service::RLChooseActionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLChooseActionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_service::RLChooseActionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_service::RLChooseActionResponse_<ContainerAllocator>& v)
  {
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVICE_MESSAGE_RLCHOOSEACTIONRESPONSE_H
