// Generated by gencpp from file robot_service/RLChooseAction.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICE_MESSAGE_RLCHOOSEACTION_H
#define ROBOT_SERVICE_MESSAGE_RLCHOOSEACTION_H

#include <ros/service_traits.h>


#include <robot_service/RLChooseActionRequest.h>
#include <robot_service/RLChooseActionResponse.h>


namespace robot_service
{

struct RLChooseAction
{

typedef RLChooseActionRequest Request;
typedef RLChooseActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RLChooseAction
} // namespace robot_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_service::RLChooseAction > {
  static const char* value()
  {
    return "6904b829fd6bdbea4739bf92ec4b118d";
  }

  static const char* value(const ::robot_service::RLChooseAction&) { return value(); }
};

template<>
struct DataType< ::robot_service::RLChooseAction > {
  static const char* value()
  {
    return "robot_service/RLChooseAction";
  }

  static const char* value(const ::robot_service::RLChooseAction&) { return value(); }
};


// service_traits::MD5Sum< ::robot_service::RLChooseActionRequest> should match 
// service_traits::MD5Sum< ::robot_service::RLChooseAction > 
template<>
struct MD5Sum< ::robot_service::RLChooseActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_service::RLChooseAction >::value();
  }
  static const char* value(const ::robot_service::RLChooseActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_service::RLChooseActionRequest> should match 
// service_traits::DataType< ::robot_service::RLChooseAction > 
template<>
struct DataType< ::robot_service::RLChooseActionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_service::RLChooseAction >::value();
  }
  static const char* value(const ::robot_service::RLChooseActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_service::RLChooseActionResponse> should match 
// service_traits::MD5Sum< ::robot_service::RLChooseAction > 
template<>
struct MD5Sum< ::robot_service::RLChooseActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_service::RLChooseAction >::value();
  }
  static const char* value(const ::robot_service::RLChooseActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_service::RLChooseActionResponse> should match 
// service_traits::DataType< ::robot_service::RLChooseAction > 
template<>
struct DataType< ::robot_service::RLChooseActionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_service::RLChooseAction >::value();
  }
  static const char* value(const ::robot_service::RLChooseActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SERVICE_MESSAGE_RLCHOOSEACTION_H
