// Generated by gencpp from file robot_service/RLMemoryStore.msg
// DO NOT EDIT!


#ifndef ROBOT_SERVICE_MESSAGE_RLMEMORYSTORE_H
#define ROBOT_SERVICE_MESSAGE_RLMEMORYSTORE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_service
{
template <class ContainerAllocator>
struct RLMemoryStore_
{
  typedef RLMemoryStore_<ContainerAllocator> Type;

  RLMemoryStore_()
    : s()
    , a()
    , r(0.0)
    , s_()  {
    }
  RLMemoryStore_(const ContainerAllocator& _alloc)
    : s(_alloc)
    , a(_alloc)
    , r(0.0)
    , s_(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _s_type;
  _s_type s;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _a_type;
  _a_type a;

   typedef double _r_type;
  _r_type r;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _s__type;
  _s__type s_;





  typedef boost::shared_ptr< ::robot_service::RLMemoryStore_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_service::RLMemoryStore_<ContainerAllocator> const> ConstPtr;

}; // struct RLMemoryStore_

typedef ::robot_service::RLMemoryStore_<std::allocator<void> > RLMemoryStore;

typedef boost::shared_ptr< ::robot_service::RLMemoryStore > RLMemoryStorePtr;
typedef boost::shared_ptr< ::robot_service::RLMemoryStore const> RLMemoryStoreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_service::RLMemoryStore_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_service::RLMemoryStore_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_service

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_service': ['/home/jingzhe/WorkSpace/ROS/mp500lwa4d_robot_env/src/robot_service/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLMemoryStore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_service::RLMemoryStore_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLMemoryStore_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_service::RLMemoryStore_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLMemoryStore_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_service::RLMemoryStore_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_service::RLMemoryStore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee95e3c395c129a7450df7cde8e1479b";
  }

  static const char* value(const ::robot_service::RLMemoryStore_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee95e3c395c129a7ULL;
  static const uint64_t static_value2 = 0x450df7cde8e1479bULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_service::RLMemoryStore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_service/RLMemoryStore";
  }

  static const char* value(const ::robot_service::RLMemoryStore_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_service::RLMemoryStore_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] s\n\
float64[] a\n\
float64 r\n\
float64[] s_\n\
";
  }

  static const char* value(const ::robot_service::RLMemoryStore_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_service::RLMemoryStore_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.a);
      stream.next(m.r);
      stream.next(m.s_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RLMemoryStore_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_service::RLMemoryStore_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_service::RLMemoryStore_<ContainerAllocator>& v)
  {
    s << indent << "s[]" << std::endl;
    for (size_t i = 0; i < v.s.size(); ++i)
    {
      s << indent << "  s[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s[i]);
    }
    s << indent << "a[]" << std::endl;
    for (size_t i = 0; i < v.a.size(); ++i)
    {
      s << indent << "  a[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.a[i]);
    }
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "s_[]" << std::endl;
    for (size_t i = 0; i < v.s_.size(); ++i)
    {
      s << indent << "  s_[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.s_[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SERVICE_MESSAGE_RLMEMORYSTORE_H
