(cl:defpackage robot_service-srv
  (:use )
  (:export
   "GETMODELSTATE"
   "<GETMODELSTATE-REQUEST>"
   "GETMODELSTATE-REQUEST"
   "<GETMODELSTATE-RESPONSE>"
   "GETMODELSTATE-RESPONSE"
   "RLCHOOSEACTION"
   "<RLCHOOSEACTION-REQUEST>"
   "RLCHOOSEACTION-REQUEST"
   "<RLCHOOSEACTION-RESPONSE>"
   "RLCHOOSEACTION-RESPONSE"
  ))

